export VITE_SERVER_HOST := "0.0.0.0"

init:
    bun create vite

dev:
    bunx --bun vite
    # -- --host 0.0.0.0
    # or bun run dev --host 0.0.0.0
build:
    bunx --bun vite -- build

# these commands probably don't belong here but I am using them anyhow
starship:
    nix-shell -p starship --run 'bash'
    echo 'eval $(starshp init bash)'

zellij:
    nix run nixpks#zellij
